// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmfkqwuTknpQp4snB-lQAEgPXsxRN46xM',
    appId: '1:766319905594:web:10ea920588a64ee0269e03',
    messagingSenderId: '766319905594',
    projectId: 'sudoku-1679e',
    authDomain: 'sudoku-1679e.firebaseapp.com',
    storageBucket: 'sudoku-1679e.appspot.com',
    measurementId: 'G-S2WPTGFRHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgO8LXQ1jlSjWfS0r2BFTtB6pMlZYIkQ',
    appId: '1:766319905594:android:547e7aaedb224d7a269e03',
    messagingSenderId: '766319905594',
    projectId: 'sudoku-1679e',
    storageBucket: 'sudoku-1679e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0LKwz_CYFgph2jMwuZzk-DTeCGRw3Do',
    appId: '1:766319905594:ios:89288daa177ece2a269e03',
    messagingSenderId: '766319905594',
    projectId: 'sudoku-1679e',
    storageBucket: 'sudoku-1679e.appspot.com',
    iosClientId: '766319905594-qmmt2jba7gvsd6lfh3j94p2o2r6j10ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.sudoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0LKwz_CYFgph2jMwuZzk-DTeCGRw3Do',
    appId: '1:766319905594:ios:834fbfb477ffe287269e03',
    messagingSenderId: '766319905594',
    projectId: 'sudoku-1679e',
    storageBucket: 'sudoku-1679e.appspot.com',
    iosClientId: '766319905594-9ctnvg3qiocke3gig5oimg4ffct4lkft.apps.googleusercontent.com',
    iosBundleId: 'com.example.sudoku.RunnerTests',
  );
}
